server:
  servlet:
    context-path: /tasktracker
  port: 8191
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/data/tasktracker;MODE=PostgreSQL;AUTO_SERVER=TRUE
    aut
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
jwt:
  secret: tasKtr4ckervtbgeekbra1ns

#server:
#  servlet:
#    context-path: /tasktracker
#  port: 8190
#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=tasktracker42
#    username: postgres
#    password: postgres1
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQL94Dialect
#        temp:
#          use_jdbc_metadata_defaults: false
#jwt:
#  secret: tasKtr4ckervtbgeekbra1ns
