server:
  servlet:
    context-path: /store
  port: 8190
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=tasktracker42
    username: postgres
    password: postgres1
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        temp:
          use_jdbc_metadata_defaults: false